remote_theme: biijuwa/eccommerce-theme
baseurl: "/blog/eckb" # the subpath of your site, e.g. /blog
url: "https://biijuwa.github.io/" # the base hostname & protocol for your site, e.g. http://example.com